name: library_demo

services:
  api:
    image: library_demo_api:latest
    container_name: library_demo_api
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    depends_on:
      - sqlserver
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server
    
    volumes:
      - library_data:/var/opt/mssql

  tests:
    image: library_demo_tests:latest
    container_name: library_demo_tests
    build:
        context: .
        dockerfile: Dockerfile
        target: test_run

volumes:
  library_data:
    name: library_data