name: library_demo

services:
  api:
    build:
      args:
        - CONFIG=Release
    ports:
      - "5201:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
  
  sqlserver:
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SuperStr0ngPassword!
      - MSSQL_PID=Developer